replicaCount: 1

image:
  api:
    repository: unishield-api
    tag: latest
  frontend:
    repository: unishield-frontend
    tag: latest

service:
  api:
    port: 8000
  frontend:
    port: 3000

ingress:
  enabled: false

resources:
  api:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
