apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unishield-ingress
  namespace: unishield-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unishield.example.com
      secretName: unishield-tls
  rules:
    - host: unishield.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: unishield-api-gateway
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unishield-frontend
                port:
                  number: 3000
